### ISSUE TITLE
[feature request] Diagrams grouping via some folders/hierarchical nesting

### ISSUE THREAD

**Issue by mikementor** [arrowboxco/community#10]
I want to convey separate projects in arrowbox and, maybe in future to share them with differetn teams

**Comment by meoyawn** [comment]
yeah we can parse your `tree` output

```
iconsearch
├── dist
│   └── index.js
├── node_modules
├── package.json
├── src
│   └── index.ts
├── tsconfig.json
└── wrangler.toml
```

first we'll need a mechanism of importing different formats: graphviz dot, PlantUML, etc

**Comment by meoyawn** [comment]
it's shipped https://arrowbox.co
